"use client"

import { useState, useMemo } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import {
  FileText,
  Copy,
  RotateCcw,
  Check,
  Download,
  AlertCircle,
  Binary,
  Hash,
  Search,
  ChevronRight,
  Upload,
  ArrowDownUp,
  Zap,
  Info,
  Eye,
  EyeOff,
  Lock
} from "lucide-react"
import Link from "next/link"
import { ALL_TOOLS } from "@/lib/constants"

type Mode = "encode" | "decode"
type Charset = "UTF-8" | "UTF-16"

interface ConversionResult {
  text: string
  error: string | null
  stats: {
    inputChars: number
    inputBytes: number
    outputChars: number
    outputBytes: number
    efficiency: number
  }
}

export default function Base64ConverterClient() {
  const [inputText, setInputText] = useState("")
  const [mode, setMode] = useState<Mode>("encode")
  const [charset, setCharset] = useState<Charset>("UTF-8")
  const [liveMode, setLiveMode] = useState(true)
  const [copied, setCopied] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")
  const [showOutput, setShowOutput] = useState(true)

  // Get relevant tools (converters)
  const relevantTools = ALL_TOOLS.filter(tool =>
    tool.href.includes('base64') ||
    tool.href.includes('ascii-to-text') ||
    tool.href.includes('text-to-ascii') ||
    tool.href.includes('url-encoder') ||
    tool.href.includes('html-entities')
  ).slice(0, 5)

  // Get other tools (random selection)
  const otherTools = ALL_TOOLS.filter(tool =>
    !tool.href.includes('base64')
  ).slice(0, 6)

  // Filter tools based on search
  const filteredRelevantTools = relevantTools.filter(tool =>
    tool.name.toLowerCase().includes(searchQuery.toLowerCase())
  )

  const conversionResult = useMemo((): ConversionResult => {
    if (!inputText.trim()) {
      return {
        text: "",
        error: null,
        stats: { inputChars: 0, inputBytes: 0, outputChars: 0, outputBytes: 0, efficiency: 0 }
      }
    }

    const stats = {
      inputChars: inputText.length,
      inputBytes: new TextEncoder().encode(inputText).length,
      outputChars: 0,
      outputBytes: 0,
      efficiency: 0
    }

    try {
      if (mode === "encode") {
        const outputText = btoa(unescape(encodeURIComponent(inputText)))
        stats.outputChars = outputText.length
        stats.outputBytes = new TextEncoder().encode(outputText).length
        if (stats.inputBytes > 0) {
          stats.efficiency = Math.round((stats.outputBytes / stats.inputBytes) * 100)
        }
        return { text: outputText, error: null, stats }
      } else {
        const outputText = decodeURIComponent(escape(atob(inputText)))
        stats.outputChars = outputText.length
        stats.outputBytes = new TextEncoder().encode(outputText).length
        if (stats.outputBytes > 0) {
          stats.efficiency = Math.round((stats.inputBytes / stats.outputBytes) * 100)
        }
        return { text: outputText, error: null, stats }
      }
    } catch (e) {
      let errorMessage = "Invalid input string."
      if (e instanceof Error) {
        if (e.message.includes("not correctly encoded")) {
          errorMessage = "Invalid Base64 string. Contains non-Base64 characters."
        } else {
          errorMessage = e.message
        }
      }
      return { text: "", error: errorMessage, stats }
    }
  }, [inputText, mode, charset, liveMode])

  const copyToClipboard = async () => {
    if (conversionResult.text) {
      await navigator.clipboard.writeText(conversionResult.text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const downloadResult = () => {
    const content = `Base64 Conversion Result
${'='.repeat(50)}

Mode: ${mode.charAt(0).toUpperCase() + mode.slice(1)}
Character Set: ${charset}

Original Input:
${inputText}

Converted Output:
${conversionResult.text}

Statistics:
- Input: ${conversionResult.stats.inputChars} chars, ${conversionResult.stats.inputBytes} bytes
- Output: ${conversionResult.stats.outputChars} chars, ${conversionResult.stats.outputBytes} bytes
- Size Change: ${mode === 'encode' ? '+' : '-'}${Math.abs(conversionResult.stats.efficiency - 100)}%

${conversionResult.error ? `Error: ${conversionResult.error}` : 'No errors'}

Generated by Tools Hub - ${new Date().toLocaleString()}
`

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `base64-conversion-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const clearAll = () => {
    setInputText("")
  }

  const loadFromFile = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = (e) => {
        const text = e.target?.result as string
        setInputText(text)
      }
      reader.readAsText(file)
    }
  }

  const handleSwap = () => {
    if (conversionResult.text && !conversionResult.error) {
      setInputText(conversionResult.text)
      setMode(mode === "encode" ? "decode" : "encode")
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50/30">
      {/* Hero Section */}
      <section className="relative py-8 px-4 sm:px-6 lg:px-8">
        <div className="relative max-w-7xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/80 backdrop-blur-sm border border-gray-200 mb-4">
              <Binary className="h-4 w-4 text-purple-600" />
              <span className="text-sm font-semibold text-gray-700">Base64 Converter</span>
            </div>

            <h1 className="text-4xl sm:text-5xl font-black text-gray-900 mb-4">
              Base64 Encoder/Decoder
            </h1>

            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Encode text to Base64 or decode Base64 to text with Unicode support
            </p>
          </div>

          {/* Main Content */}
          <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
            {/* Left Sidebar */}
            <div className="lg:col-span-1 space-y-4">
              {/* Search */}
              <div className="bg-white rounded-2xl p-4 border border-gray-200">
                <div className="flex items-center gap-2 mb-3">
                  <Search className="h-4 w-4 text-gray-500" />
                  <h3 className="text-sm font-bold text-gray-900">Search Tools</h3>
                </div>
                <Input
                  type="text"
                  placeholder="Search tools..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="border-gray-200 rounded-xl"
                />
              </div>

              {/* Security Note */}
              <div className="bg-white rounded-2xl p-4 border-2 border-yellow-200">
                <div className="flex items-center gap-2 mb-3">
                  <Lock className="h-4 w-4 text-yellow-600" />
                  <h3 className="text-sm font-bold text-gray-900">Security Note</h3>
                </div>
                <p className="text-xs text-gray-600">
                  Base64 is an <strong>encoding</strong> method, not encryption. It is not secure for protecting sensitive data.
                </p>
              </div>

              {/* Relevant Tools */}
              <div className="bg-white rounded-2xl p-4 border border-gray-200">
                <div className="flex items-center gap-2 mb-3">
                  <Zap className="h-4 w-4 text-purple-600" />
                  <h3 className="text-sm font-bold text-gray-900">Relevant Tools</h3>
                </div>
                <div className="space-y-1">
                  {(searchQuery ? filteredRelevantTools : relevantTools).map((tool, index) => (
                    <Link
                      key={index}
                      href={tool.href}
                      className="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-50 transition-colors group"
                    >
                      <ChevronRight className="h-3 w-3 text-gray-400 group-hover:text-purple-600" />
                      <span className="text-xs text-gray-700 group-hover:text-purple-600 font-medium">
                        {tool.name}
                      </span>
                    </Link>
                  ))}
                </div>
              </div>

              {/* Other Tools */}
              <div className="bg-white rounded-2xl p-4 border border-gray-200">
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="h-4 w-4 text-orange-600" />
                  <h3 className="text-sm font-bold text-gray-900">Other Tools</h3>
                </div>
                <div className="space-y-1">
                  {otherTools.map((tool, index) => (
                    <Link
                      key={index}
                      href={tool.href}
                      className="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-50 transition-colors group"
                    >
                      <ChevronRight className="h-3 w-3 text-gray-400 group-hover:text-orange-600" />
                      <span className="text-xs text-gray-700 group-hover:text-orange-600 font-medium">
                        {tool.name}
                      </span>
                    </Link>
                  ))}
                </div>
              </div>
            </div>

            {/* Main Content Area */}
            <div className="lg:col-span-3 space-y-6">
              {/* Settings Card */}
              <div className="bg-white rounded-2xl p-6 border border-gray-200">
                <div className="flex flex-col md:flex-row md:items-center md:justify-between">
                  <h3 className="text-base font-bold text-gray-900 mb-4 md:mb-0">Conversion Settings</h3>
                  <div className="flex items-center gap-4">
                    <Button
                      variant={mode === 'encode' ? 'default' : 'outline'}
                      onClick={() => setMode('encode')}
                      className="flex-1"
                    >
                      Encode
                    </Button>
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={handleSwap}
                      disabled={!conversionResult.text || !!conversionResult.error}
                    >
                      <ArrowDownUp className="h-4 w-4" />
                    </Button>
                    <Button
                      variant={mode === 'decode' ? 'default' : 'outline'}
                      onClick={() => setMode('decode')}
                      className="flex-1"
                    >
                      Decode
                    </Button>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4 pt-4 border-t border-gray-200">
                  {/* Character Set */}
                  <div>
                    <label className="block text-sm font-semibold text-gray-700 mb-2">
                      Character Set
                    </label>
                    <select
                      value={charset}
                      onChange={(e) => setCharset(e.target.value as Charset)}
                      className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:border-purple-500 focus:ring-1 focus:ring-purple-500 transition-all"
                    >
                      <option value="UTF-8">UTF-8 (Default)</option>
                      <option value="UTF-16">UTF-16</option>
                    </select>
                  </div>

                  {/* Live Mode */}
                  <div className="flex items-end">
                    <label className="flex items-center gap-3 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={liveMode}
                        onChange={(e) => setLiveMode(e.target.checked)}
                        className="w-4 h-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500"
                      />
                      <div>
                        <span className="text-sm font-semibold text-gray-900">Live Mode</span>
                        <p className="text-xs text-gray-500">Convert as you type</p>
                      </div>
                    </label>
                  </div>
                </div>
              </div>

              {/* Input and Output in Parallel */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Input Card */}
                <div className="bg-white rounded-2xl p-6 border border-gray-200">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="text-base font-bold text-gray-900">Input</h3>
                      <p className="text-sm text-gray-600">{mode === 'encode' ? 'Text to encode' : 'Base64 to decode'}</p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => document.getElementById('file-upload')?.click()}
                        className="rounded-lg border-gray-300"
                      >
                        <Upload className="h-4 w-4 mr-2" />
                        Upload
                      </Button>
                      <input
                        id="file-upload"
                        type="file"
                        accept=".txt"
                        onChange={loadFromFile}
                        className="hidden"
                      />
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={clearAll}
                        disabled={!inputText}
                        className="rounded-lg border-gray-300"
                      >
                        <RotateCcw className="h-4 w-4 mr-2" />
                        Clear
                      </Button>
                    </div>
                  </div>

                  <Textarea
                    value={inputText}
                    onChange={(e) => setInputText(e.target.value)}
                    placeholder={mode === 'encode' ? 'Enter text...' : 'Enter Base64...'}
                    className="min-h-[300px] resize-none font-mono text-sm border-gray-300 rounded-lg focus:border-purple-500 focus:ring-1 focus:ring-purple-500"
                  />

                  <div className="flex items-center justify-between mt-3 text-sm text-gray-600">
                    <span>{conversionResult.stats.inputChars} chars</span>
                    <span>{conversionResult.stats.inputBytes} bytes</span>
                  </div>
                </div>

                {/* Output Card */}
                <div className="bg-white rounded-2xl p-6 border-2 border-purple-200">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <h3 className="text-base font-bold text-gray-900">Output</h3>
                      <p className="text-sm text-gray-600">{mode === 'encode' ? 'Base64 result' : 'Decoded text'}</p>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setShowOutput(!showOutput)}
                        className="rounded-lg border-gray-300"
                      >
                        {showOutput ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={copyToClipboard}
                        disabled={!conversionResult.text}
                        className="rounded-lg border-gray-300"
                      >
                        {copied ? (
                          <>
                            <Check className="h-4 w-4 mr-2" />
                            Copied!
                          </>
                        ) : (
                          <>
                            <Copy className="h-4 w-4 mr-2" />
                            Copy
                          </>
                        )}
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={downloadResult}
                        className="rounded-lg border-gray-300"
                      >
                        <Download className="h-4 w-4 mr-2" />
                        Download
                      </Button>
                    </div>
                  </div>

                  {showOutput ? (
                    <Textarea
                      value={conversionResult.error ? `Error: ${conversionResult.error}` : conversionResult.text}
                      readOnly
                      className={`min-h-[300px] resize-none font-mono text-base rounded-lg ${
                        conversionResult.error
                          ? 'bg-red-50/50 border-red-200 text-red-700'
                          : 'bg-purple-50/50 border-purple-200'
                      }`}
                      placeholder="Result will appear here..."
                    />
                  ) : (
                    <div className="min-h-[300px] bg-gray-100 rounded-md flex items-center justify-center border-2 border-dashed">
                      <div className="text-center text-gray-500">
                        <EyeOff className="h-8 w-8 mx-auto mb-2" />
                        <p>Output hidden for privacy</p>
                      </div>
                    </div>
                  )}

                  {showOutput && (
                    <div className="flex items-center justify-between mt-3 text-sm text-gray-600">
                      <span>{conversionResult.stats.outputChars} chars</span>
                      <span>{conversionResult.stats.outputBytes} bytes</span>
                      {conversionResult.stats.efficiency > 0 && (
                        <span className="font-semibold text-purple-600">
                          {mode === 'encode' ? '+' : '-'}{Math.abs(conversionResult.stats.efficiency - 100)}% size
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {/* Error Display */}
              {conversionResult.error && (
                <div className="bg-red-50 border border-red-200 rounded-2xl p-4">
                  <div className="flex items-center gap-2">
                    <AlertCircle className="h-4 w-4 text-red-600" />
                    <span className="font-bold text-red-900 text-sm">Error</span>
                  </div>
                  <p className="text-sm text-red-800 mt-2">{conversionResult.error}</p>
                </div>
              )}
            </div>
          </div>

          {/* Full-width About Section */}
          <div className="mt-8 bg-white rounded-2xl p-8 border border-gray-200">
            <div className="max-w-full">
              <div className="flex items-center gap-2 mb-4">
                <Info className="h-5 w-5 text-purple-600" />
                <h2 className="text-2xl font-bold text-gray-900">About Base64 Converter</h2>
              </div>

              <div className="prose prose-sm text-gray-600 max-w-none">
                <p className="mb-4">
                  The Base64 Converter is a versatile online tool for encoding plain text into Base64 strings and decoding Base64 strings back into their original text form. This tool fully supports Unicode (UTF-8), allowing for the correct encoding and decoding of international characters, symbols, and emojis.
                </p>

                <div className="grid md:grid-cols-2 gap-6 my-6">
                  <div>
                    <h3 className="text-lg font-bold text-gray-900 mb-3">Key Features</h3>
                    <ul className="space-y-2">
                      <li className="flex items-start gap-2">
                        <span className="text-purple-600 mt-1">•</span>
                        <span><strong>Full Unicode Support:</strong> Correctly handles multi-byte characters, emojis, and international symbols.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-purple-600 mt-1">•</span>
                        <span><strong>Bidirectional:</strong> Instantly switch between encoding and decoding.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-purple-600 mt-1">•</span>
                        <span><strong>File Handling:</strong> Upload text files for conversion and download the results.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-purple-600 mt-1">•</span>
                        <span><strong>Live Mode:</strong> See results update in real-time as you type.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-purple-600 mt-1">•</span>
                        <span><strong>Detailed Stats:</strong> Monitor character/byte counts and size efficiency.</span>
                      </li>
                    </ul>
                  </div>

                  <div>
                    <h3 className="text-lg font-bold text-gray-900 mb-3">How to Use</h3>
                    <ol className="space-y-2">
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-purple-600">1.</span>
                        <span>Select "Encode" or "Decode" mode.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-purple-600">2.</span>
                        <span>Paste your text or upload a file.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-purple-600">3.</span>
                        <span>The result appears instantly in the output box.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="font-bold text-purple-600">4.</span>
                        <span>Use the copy or download buttons to save your result.</span>
                      </li>
                    </ol>
                  </div>
                </div>

                <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 my-6">
                  <h3 className="text-lg font-bold text-gray-900 mb-2">Unicode Example</h3>
                  <div className="grid md:grid-cols-2 gap-3 text-sm">
                    <div>
                      <strong className="text-gray-900">Original Text:</strong>
                      <code className="block bg-white px-2 py-1 rounded mt-1 font-mono">Hello, 世界! 👋</code>
                    </div>
                    <div>
                      <strong className="text-gray-900">Base64 Encoded:</strong>
                      <code className="block bg-white px-2 py-1 rounded mt-1 font-mono text-xs break-all">SGVsbG8sIOS4lueVjCEg8J+Riw==</code>
                    </div>
                  </div>
                </div>

                <h3 className="text-lg font-bold text-gray-900 mb-3">What is Base64?</h3>
                <p className="mb-4">
                  Base64 is a binary-to-text encoding scheme that represents binary data in an ASCII string format. It's commonly used to transmit data that might otherwise be corrupted by systems that only handle text. It is not a form of encryption and provides no security.
                </p>

                <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                  <h3 className="text-lg font-bold text-gray-900 mb-2">Privacy & Security</h3>
                  <p>
                    All conversions happen directly in your browser. Your data never leaves your device and is not sent to any server. This ensures complete privacy and security for all your conversions.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}