import { NextResponse } from 'next/server'

const emojiToTextMap: Record<string, string> = {
  "😀": "grinning face",
  "😂": "face with tears of joy",
  "❤️": "red heart",
  "👍": "thumbs up",
  "🎉": "party popper",
  "😢": "crying face",
  "🔥": "fire",
  "😊": "smiling face with smiling eyes",
  "😎": "smiling face with sunglasses",
  "🤔": "thinking face",
  "⭐": "star",
  "🌟": "glowing star",
  "✨": "sparkles",
  "💖": "sparkling heart",
  "😍": "smiling face with heart eyes",
  "🙌": "raising hands",
  "👏": "clapping hands",
  "🎊": "confetti ball",
  "🎈": "balloon",
  "🎂": "birthday cake",
  "😘": "face blowing a kiss",
  "😉": "winking face",
  "😜": "winking face with tongue",
  "😝": "squinting face with tongue",
  "😋": "face savoring food",
  "😛": "face with tongue",
  "😴": "sleeping face",
  "😪": "sleepy face",
  "😵": "dizzy face",
  "🤐": "zipper-mouth face",
  "🤗": "hugging face",
  "🤭": "face with hand over mouth",
  "🤫": "shushing face",
  "🤥": "lying face",
  "😶": "face without mouth",
  "😐": "neutral face",
  "😑": "expressionless face",
  "😬": "grimacing face",
  "🙄": "face with rolling eyes",
  "😯": "hushed face",
  "😦": "frowning face with open mouth",
  "😧": "anguished face",
  "😮": "face with open mouth",
  "😲": "astonished face",
  "😱": "face screaming in fear",
  "😨": "fearful face",
  "😰": "anxious face with sweat",
  "😥": "sad but relieved face",
  "😭": "loudly crying face",
  "😤": "face with steam from nose",
  "😠": "angry face",
  "😡": "pouting face",
  "🤬": "face with symbols on mouth",
  "😈": "devil face",
  "👿": "angry face with horns",
  "💀": "skull",
  "☠️": "skull and crossbones",
  "👻": "ghost",
  "👽": "alien",
  "🤖": "robot face",
  "😺": "grinning cat face",
  "😸": "grinning cat face with smiling eyes",
  "😹": "cat face with tears of joy",
  "😻": "smiling cat face with heart eyes",
  "😼": "cat face with wry smile",
  "😽": "kissing cat face",
  "🙀": "weary cat face",
  "😿": "crying cat face",
  "😾": "pouting cat face",
  "🐱": "cat face",
  "🐶": "dog face",
  "🐭": "mouse face",
  "🐹": "hamster face",
  "🐰": "rabbit face",
  "🦊": "fox face",
  "🐻": "bear face",
  "🐼": "panda face",
  "🐨": "koala face",
  "🐯": "tiger face",
  "🦁": "lion face",
  "🐮": "cow face",
  "🐷": "pig face",
  "🐽": "pig nose",
  "🐸": "frog face",
  "🐵": "monkey face",
  "🙈": "see-no-evil monkey",
  "🙉": "hear-no-evil monkey",
  "🙊": "speak-no-evil monkey",
  "🐒": "monkey",
  "🐔": "chicken",
  "🐧": "penguin",
  "🐦": "bird",
  "🐤": "baby chick",
  "🐣": "hatching chick",
  "🐥": "front-facing baby chick",
  "🦆": "duck",
  "🦅": "eagle",
  "🦉": "owl",
  "🦇": "bat",
  "🐺": "wolf face",
  "🐗": "boar",
  "🐴": "horse face",
  "🦄": "unicorn face",
  "🐝": "honeybee",
  "🐛": "bug",
  "🦋": "butterfly",
  "🐌": "snail",
  "🐞": "lady beetle",
  "🐜": "ant",
  "🦗": "cricket",
  "🕷️": "spider",
  "🦂": "scorpion",
  "🐢": "turtle",
  "🐍": "snake",
  "🦎": "lizard",
  "🦖": "t-rex",
  "🦕": "sauropod",
  "🐙": "octopus",
  "🦑": "squid",
  "🦐": "shrimp",
  "🦞": "lobster",
  "🦀": "crab",
  "🐡": "blowfish",
  "🐠": "tropical fish",
  "🐟": "fish",
  "🐬": "dolphin",
  "🐳": "spouting whale",
  "🐋": "whale",
  "🦈": "shark",
  "🐊": "crocodile",
  "🐅": "tiger",
  "🐆": "leopard",
  "🦓": "zebra",
  "🦍": "gorilla",
  "🐘": "elephant",
  "🦛": "hippopotamus",
  "🦏": "rhinoceros",
  "🐪": "camel",
  "🐫": "two-hump camel",
  "🦒": "giraffe",
  "🐃": "water buffalo",
  "🐂": "ox",
  "🐄": "cow",
  "🐎": "horse",
  "🐖": "pig",
  "🐏": "ram",
  "🐑": "sheep",
  "🦙": "llama",
  "🐐": "goat",
  "🐉": "dragon",
  "🐲": "dragon face",
  "🌸": "cherry blossom",
  "🌺": "hibiscus",
  "🌻": "sunflower",
  "🌹": "rose",
  "🥀": "wilted flower",
  "🌷": "tulip",
  "🌼": "blossom",
  "🌿": "herb",
  "🍀": "four leaf clover",
  "🎋": "tanabata tree",
  "🎍": "pine decoration",
  "🌾": "sheaf of rice",
  "🌵": "cactus",
  "🎄": "christmas tree",
  "🌲": "evergreen tree",
  "🌳": "deciduous tree",
  "🌴": "palm tree",
  "🌱": "seedling",
  "☘️": "shamrock",
  "🍄": "mushroom",
  "🌰": "chestnut",
  "🍞": "bread",
  "🥐": "croissant",
  "🥖": "baguette bread",
  "🥨": "pretzel",
  "🥯": "bagel",
  "🧀": "cheese wedge",
  "🥚": "egg",
  "🍳": "cooking",
  "🧈": "butter",
  "🥞": "pancakes",
  "🧇": "waffle",
  "🥓": "bacon",
  "🥩": "cut of meat",
  "🍗": "poultry leg",
  "🍖": "meat on bone",
  "🌭": "hot dog",
  "🍔": "hamburger",
  "🍟": "french fries",
  "🍕": "pizza",
  "🌮": "taco",
  "🌯": "burrito",
  "🥙": "stuffed flatbread",
  "🥘": "shallow pan of food",
  "🍝": "spaghetti",
  "🍜": "steaming bowl",
  "🍲": "pot of food",
  "🍛": "curry rice",
  "🍣": "sushi",
  "🍱": "bento box",
  "🥟": "dumpling",
  "🦪": "oyster",
  "🍤": "fried shrimp",
  "🍙": "rice ball",
  "🍚": "cooked rice",
  "🍘": "rice cracker",
  "🍥": "fish cake with swirl",
  "🥠": "fortune cookie",
  "🥮": "moon cake",
  "🍢": "oden",
  "🍡": "dango",
  "🍧": "shaved ice",
  "🍨": "ice cream",
  "🍦": "soft ice cream",
  "🥧": "pie",
  "🧁": "cupcake",
  "🍰": "shortcake",
  "🍮": "custard",
  "🍭": "lollipop",
  "🍬": "candy",
  "🍫": "chocolate bar",
  "🍿": "popcorn",
  "🍩": "doughnut",
  "🍪": "cookie",
  "🥜": "peanuts",
  "🍯": "honey pot",
  "🥛": "glass of milk",
  "🍼": "baby bottle",
  "☕": "hot beverage",
  "🫖": "teapot",
  "🍵": "teacup without handle",
  "🧃": "beverage box",
  "🥤": "cup with straw",
  "🧋": "bubble tea",
  "🍶": "sake",
  "🍺": "beer mug",
  "🍻": "clinking beer mugs",
  "🥂": "clinking glasses",
  "🍷": "wine glass",
  "🥃": "tumbler glass",
  "🍸": "cocktail glass",
  "🍹": "tropical drink",
  "🧉": "mate",
  "🍾": "champagne",
  "🧊": "ice",
  "🥄": "spoon",
  "🍴": "fork and knife",
  "🍽️": "fork and knife with plate",
  "🥣": "bowl with spoon",
  "🥡": "takeout box",
  "🥢": "chopsticks",
  "🧂": "salt",
  "⚽": "soccer ball",
  "🏀": "basketball",
  "🏈": "american football",
  "⚾": "baseball",
  "🥎": "softball",
  "🎾": "tennis",
  "🏐": "volleyball",
  "🏉": "rugby football",
  "🥏": "flying disc",
  "🎱": "pool 8 ball",
  "🪀": "yo-yo",
  "🏓": "ping pong",
  "🏸": "badminton",
  "🏒": "ice hockey",
  "🏑": "field hockey",
  "🥍": "lacrosse",
  "🏏": "cricket game",
  "🪃": "boomerang",
  "🥅": "goal net",
  "⛳": "flag in hole",
  "🪁": "kite",
  "🏹": "bow and arrow",
  "🎣": "fishing pole",
  "🤿": "diving mask",
  "🥊": "boxing glove",
  "🥋": "martial arts uniform",
  "🎽": "running shirt",
  "🛹": "skateboard",
  "🛷": "sled",
  "⛸️": "ice skate",
  "🥌": "curling stone",
  "🎿": "skis",
  "⛷️": "skier",
  "🏂": "snowboarder",
  "🪂": "parachute",
  "🏋️": "person lifting weights",
  "🤸": "person cartwheeling",
  "⛹️": "person bouncing ball",
  "👨": "man",
  "👩": "woman",
  "🧑": "person",
  "👨‍🦱": "man curly hair",
  "👩‍🦱": "woman curly hair",
  "👨‍🦰": "man red hair",
  "👩‍🦰": "woman red hair",
  "👨‍🦳": "man white hair",
  "👩‍🦳": "woman white hair",
  "👨‍🦲": "man bald",
  "👩‍🦲": "woman bald",
  "🧔": "man beard",
  "👱": "person blond hair",
  "👨‍⚕️": "man health worker",
  "👩‍⚕️": "woman health worker",
  "👨‍🎓": "man student",
  "👩‍🎓": "woman student",
  "👨‍🏫": "man teacher",
  "👩‍🏫": "woman teacher",
  "👨‍⚖️": "man judge",
  "👩‍⚖️": "woman judge",
  "👨‍🌾": "man farmer",
  "👩‍🌾": "woman farmer",
  "👨‍🍳": "man cook",
  "👩‍🍳": "woman cook",
  "👨‍🔧": "man mechanic",
  "👩‍🔧": "woman mechanic",
  "👨‍🏭": "man factory worker",
  "👩‍🏭": "woman factory worker",
  "👨‍💼": "man office worker",
  "👩‍💼": "woman office worker",
  "👨‍🔬": "man scientist",
  "👩‍🔬": "woman scientist",
  "👨‍💻": "man technologist",
  "👩‍💻": "woman technologist",
  "👨‍🎤": "man singer",
  "👩‍🎤": "woman singer",
  "👨‍🎨": "man artist",
  "👩‍🎨": "woman artist",
  "👨‍✈️": "man pilot",
  "👩‍✈️": "woman pilot",
  "👨‍🚀": "man astronaut",
  "👩‍🚀": "woman astronaut",
  "👨‍🚒": "man firefighter",
  "👩‍🚒": "woman firefighter",
  "👮": "police officer",
  "🕵️": "detective",
  "💂": "guard",
  "🥷": "ninja",
  "👷": "construction worker",
  "🤴": "prince",
  "👸": "princess",
  "👳": "person wearing turban",
  "👲": "person with skullcap",
  "🧕": "woman with headscarf",
  "🤵": "person in tuxedo",
  "🤰": "pregnant woman",
  "🤱": "breast-feeding",
  "👼": "baby angel",
  "🎅": "santa claus",
  "🤶": "mrs claus",
  "🦸": "superhero",
  "🦹": "supervillain",
  "🧙": "mage",
  "🧚": "fairy",
  "🧛": "vampire",
  "🧜": "merperson",
  "🧝": "elf",
  "🧞": "genie",
  "🧟": "zombie",
  "💆": "person getting massage",
  "💇": "person getting haircut",
  "🚶": "person walking",
  "🧍": "person standing",
  "👨‍🦯": "man with white cane",
  "👩‍🦯": "woman with white cane",
  "👨‍🦼": "man in motorized wheelchair",
  "👩‍🦼": "woman in motorized wheelchair",
  "👨‍🦽": "man in manual wheelchair",
  "👩‍🦽": "woman in manual wheelchair",
  "🏃": "person running",
  "💃": "woman dancing",
  "🕺": "man dancing",
  "🕴️": "person in suit levitating",
  "👯": "people with bunny ears",
  "🧖": "person in steamy room",
  "🧗": "person climbing",
  "🏇": "horse racing",
  "🏌️": "person golfing",
  "🏄": "person surfing",
  "🚣": "person rowing boat",
  "🏊": "person swimming",
  "🚴": "person biking",
  "🚵": "person mountain biking",
  "🤼": "people wrestling",
  "🤽": "person playing water polo",
  "🤹": "person juggling",
  "🛀": "person taking bath",
  "🛌": "person in bed",
  "👭": "women holding hands",
  "👫": "woman and man holding hands",
  "👬": "men holding hands",
  "💏": "kiss",
  "👨‍❤️‍💋‍👨": "kiss man man",
  "👩‍❤️‍💋‍👩": "kiss woman woman",
  "💑": "couple with heart",
  "👨‍❤️‍👨": "couple with heart man man",
  "👩‍❤️‍👩": "couple with heart woman woman",
  "👪": "family",
  "👨‍👩‍👦": "family man woman boy",
  "👨‍👩‍👧": "family man woman girl",
  "👨‍👩‍👧‍👦": "family man woman girl boy",
}

export async function GET() {
  try {
    return NextResponse.json(emojiToTextMap)
  } catch (_error) {
    return NextResponse.json(
      { error: 'Failed to fetch emoji mapping data' },
      { status: 500 }
    )
  }
}
